version: '3.8'

services:
  client:
    build:
      context: ./Guitutor - client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./Guitutor - server
      dockerfile: Dockerfile
